# Generated by Django 2.2.4 on 2019-12-19 00:27

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='description',
            field=wagtail.core.fields.RichTextField(default='', verbose_name='Description'),
            preserve_default=False,
        ),
    ]
